AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 60

Parameters:
  StackNamePrefix:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Environment prefix for stack resources

  SenderCronSchedule:
    Type: String
    Default: "cron(0,10,20,30,40,50 * ? * * *)" # "0 0 5 31 2 ?"  fake scheudle will never happen
    Description: Cron schedule for the lambda

Resources:
  TwilioWebHookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "twilio-webhook-${StackNamePrefix}"
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post

  SendRemindersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "twilio-send-reminders-${StackNamePrefix}"
      CodeUri: send_scheduled_reminders/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          S3_BUCKET: "twilio-apps"
          S3_KEY_PREFIX: !Ref StackNamePrefix
      Layers:
        - !Ref TwilioLayer
      Policies:
        - S3CrudPolicy:
            BucketName: "twilio-apps"
        - Statement:
            - Sid: Secrets
              Action:
                - secretsmanager:DescribeSecret
                - secretsmanager:GetSecretValue
              Effect: Allow
              Resource:
                - "*"
      Events:
        CronEvent:
          Properties:
            Schedule: !Ref SenderCronSchedule
          Type: Schedule

  TwilioLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Domain code for the app
      ContentUri: common_layer/
      CompatibleRuntimes:
        - python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TwilioWebHookApi:
    Description: "API Gateway endpoint URL for Prod stage for TwilioWebHookApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
